/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finallab;

import Controlador.Datos;
import Controlador.Utiles;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Erick Mayorga
 */
public class Interfaz extends javax.swing.JFrame {
    Datos datos;
    JButton unBoton;
    public static int contadorLabel=20;

    /** Creates new form Interfaz */
    public Interfaz() {
  
      initComponents();
        
        super.setVisible(true);
        super.setSize(400,400);
        super.setLocationRelativeTo(null);

        agregarOtros();
             contarTiempo();
        
            
        //setLocationRelativeTo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        codigoG = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(310, 340));
        jPanel2.setLayout(null);

        jButton2.setText("Pop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(210, 280, 100, 23);

        jLabel2.setText("20s");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(250, 330, 40, 20);

        codigoG.setEditable(false);
        codigoG.setColumns(20);
        codigoG.setRows(5);
        jScrollPane2.setViewportView(codigoG);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(180, 30, 170, 220);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Datos.Piladatos.pop();
      codigoG.setText(Datos.Piladatos.generagraph());
        



    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void agregarOtros(){
        datos=new Datos(jPanel2);
        datos.llenarListaL();        
    }
    public void contarTiempo(){
        while(contadorLabel>0){
           
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
             contadorLabel--;
             jLabel2.setText(String.valueOf(contadorLabel));
            
        }
        
    }
    
    
    public static String seteaTexto(){
        String texto=Datos.Piladatos.generagraph();
        return texto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea codigoG;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
